version: '2'
services:
    lookbrbackendv2-app:
        image: lookbrbackendv2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lookbrbackendv2-mysql:3306/lookbrbackendv2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lookbrbackendv2-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    lookbrbackendv2-mysql:
        extends:
            file: mysql.yml
            service: lookbrbackendv2-mysql
    lookbrbackendv2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lookbrbackendv2-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
